### ISSUE TITLE
Tracking LightZone in the package ecosystem

### ISSUE THREAD

**Issue by luzpaz** [ktgw0316/LightZone#300]
<a href="https://repology.org/project/lightzone/versions">
    <img src="https://repology.org/badge/vertical-allrepos/lightzone.svg?columns=3" alt="Packaging status">
</a>

### Linux

- [ ] Fedora https://github.com/ktgw0316/LightZone/issues/306
- [X] flatpak https://flathub.org/apps/io.github.ktgw0316.LightZone

### FreeBSD

- [ ] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238664

### Windows

- [ ] Chocolatey (https://github.com/chocolatey-community/chocolatey-package-requests/issues/1438)

### MacOS

- [ ] Homebrew Casks

**Comment by luzpaz** [comment]
I was going to submit LightZone to the package repos but maybe wait till #301 is fixed ?

**Comment by ktgw0316** [comment]
#301 is fixed now, but I don't recommend to submit beta versions, so please wait until stable v5.0.0 is released.

Please feel free to submit v4.2.4 / 4.2.5.  I myself did that for the winget.

**Comment by luzpaz** [comment]
Bumped FreeBSD ticket (added to OP)

**Comment by luzpaz** [comment]
Added Chocolatey request

**Comment by luzpaz** [comment]
Soft bump on ETA of v5.0.0 ?

**Comment by hfiguiere** [comment]
you can add Flatpak on Flathub https://flathub.org/apps/io.github.ktgw0316.LightZone

**Comment by luzpaz** [comment]
is there an ETA on a 5.0.0 release ?

**Comment by Jozxyqk6** [comment]
> you can add Flatpak on Flathub https://flathub.org/apps/io.github.ktgw0316.LightZone

User on the linuxmint forum reports that, after a long time using it with pleasure, the flathub version stopped working about a month ago. Did something change?

Versions:
Linux Mint 22 (user also tried it with fresh install)
Lightzone 4.2.5 (flathub)

Report (in Dutch): https://forums.linuxmint.com/viewtopic.php?t=434628

**Comment by luzpaz** [comment]
@Jozxyqk6 please open a ticket in https://github.com/flathub/io.github.ktgw0316.LightZone (flatpak repo)

cc @hfiguiere
